<?php


class BMIViewDashboard extends BMIView {

	public function __construct() {

	}

	public function display($tpl = null)
	{
		return parent::display($tpl); // TODO: Change the autogenerated stub
	}

}

$new = new BMIViewDashboard();
$new->display();

?>