<?php


class BMIViewDebug extends BMIView {

	protected $items;
	protected $emails;

	public function __construct() {
	}

	public function display($tpl = null)
	{
		$this->items = $this->loadModel();
		return parent::display($tpl); // TODO: Change the autogenerated stub
	}



}

$new = new BMIViewDebug();
$new->display();

?>