<?php


class BMIViewEmails extends BMIView {

	public function __construct() {
		$this->display();
	}

	public function display($tpl = null)
	{
		$this->emails = $this->getListEmail();
		return parent::display($tpl); // TODO: Change the autogenerated stub
	}

	private function getListEmail(){
		global $wpdb;
		$result = $wpdb->get_results("SELECT email FROM {$wpdb->prefix}bmi_contacts");
		return $result;
	}

}

$new = new BMIViewEmails();

?>